apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: o6e3g5b69-go 
  janus-idp.io/tekton: o6e3g5b69-go
  backstage.io/kubernetes-id: o6e3g5b69-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o6e3g5b69-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml